<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <RootNamespace>SCS_Mod_Helper</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	  <ApplicationManifest>app.manifest</ApplicationManifest>
	  <ApplicationIcon>Images\AppIcon.ico</ApplicationIcon>
	  <AssemblyName>SCS Mod Helper</AssemblyName>
	  <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Window1.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Modding\PaintJob\arrow.png" />
    <None Remove="App.config" />
    <None Remove="Images\AppIcon.png" />
    <None Remove="Trucks\DefaultTrucks.db" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Modding\PaintJob\arrow.png" />
    <Resource Include="Images\AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="App.config" />
    <EmbeddedResource Include="Trucks\DefaultTrucks.db">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.Wpf" Version="3.1.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Pfim" Version="0.11.4" />
    <PackageReference Include="PixiEditor.ColorPicker" Version="3.4.2.3" />
    <PackageReference Include="System.Drawing.Common" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\AppIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Modding\Accessories\AccAddon\AccAddonHistory.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>AccAddonHistory.settings</DependentUpon>
    </Compile>
    <Compile Update="Setting\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Language\en-US_English(US).txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Language\example.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modding\Accessories\AccAddon\AccAddonHistory.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>AccAddonHistory.Designer.cs</LastGenOutput>
    </None>
    <None Update="Setting\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
