//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCS_Mod_Helper.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.10.0.0")]
    internal sealed partial class PathHistories : global::System.Configuration.ApplicationSettingsBase {
        
        private static PathHistories defaultInstance = ((PathHistories)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PathHistories())));
        
        public static PathHistories Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEDLocation {
            get {
                return ((string)(this["DEDLocation"]));
            }
            set {
                this["DEDLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChooseModelHistory {
            get {
                return ((string)(this["ChooseModelHistory"]));
            }
            set {
                this["ChooseModelHistory"] = value;
            }
        }
    }
}
